spring.application.name=banco_sociedad

spring.datasource.url=jdbc:mysql://localhost:3306/banco_sociedad?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=user_ADMIN1

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# EJECUCIONES JOBS
#spring.batch.job.name=dailyTransactionJob
spring.batch.job.name=monthlyInterestJob
#spring.batch.job.name=annualStatementJob

# Spring Batch
spring.batch.jdbc.initialize-schema=always
